# Generated by Django 4.2.9 on 2024-07-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lampadaire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_unique', models.CharField(max_length=200)),
                ('id_lampadaire', models.CharField(max_length=200)),
                ('commune', models.CharField(max_length=100)),
                ('zone', models.IntegerField(blank=True, null=True)),
                ('photo_jour', models.CharField(max_length=200)),
                ('photo_jour_url', models.URLField(blank=True, null=True)),
                ('photo_nuit_url', models.URLField(blank=True, null=True)),
                ('submitted_by', models.CharField(max_length=200)),
                ('validation', models.BooleanField()),
                ('observation', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('info', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
