# Generated by Django 4.2.9 on 2024-07-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lampadaire',
            name='photo_nuit',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
