# Generated by Django 4.2.9 on 2024-07-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_lampadaire_photo_nuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampadaire',
            name='zone',
            field=models.CharField(blank=True, null=True),
        ),
    ]
