# Generated by Django 4.2.9 on 2024-07-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_lampadaire_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampadaire',
            name='validation',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
